# Generated by Django 4.0.3 on 2022-03-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompoundName', models.CharField(help_text='اسم المحافظة يجب ان يكون غير مدرج من قبل', max_length=20, unique=True, verbose_name='المحافظه')),
                ('GoverneratesId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.governerates', verbose_name='كود المحافظة')),
            ],
            options={
                'verbose_name': 'المجمع',
                'verbose_name_plural': 'المجمعات',
                'ordering': ['CompoundName'],
            },
        ),
    ]
