# Generated by Django 4.0.3 on 2022-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0003_activities_alter_compound_compoundname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationunitsdata',
            options={'ordering': ['UnitNumber'], 'verbose_name': 'بيانات الوحدة المخصصة', 'verbose_name_plural': 'بيانات الوحدة المخصصة'},
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='UnitNumber',
            field=models.PositiveIntegerField(default=0, verbose_name=' رقم الوحدة '),
        ),
    ]
