# Generated by Django 4.0.3 on 2022-03-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0005_legalentity_specificationunitsdata_ownerunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandOperatingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LandOperatingStatusName', models.CharField(help_text='حالة القطعه التشغيلية الحالية', max_length=40, unique=True, verbose_name=' حاله القطعه التشغيلية')),
            ],
            options={
                'verbose_name': 'حالة القطعه التشغيلية ',
                'verbose_name_plural': 'حالات القطعه التشغيلية',
                'ordering': ['LandOperatingStatusName'],
            },
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='CommitteeNumber',
            field=models.PositiveIntegerField(default=0, verbose_name=' رقم اللجنة '),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='DeclarationModification',
            field=models.BooleanField(default=False, help_text='هل يوجد تصريح بالتعديل  ', verbose_name=' تصريح بالتعديل'),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='HandedDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استلام الوحدة'),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='Has_Electric_Meter',
            field=models.BooleanField(default=False, help_text='هل يوجد عداد كهرباء', verbose_name='هل يوجد عداد الكهرباء  '),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='Has_Finance',
            field=models.BooleanField(default=False, help_text='هل يوجد تمويل', verbose_name=' هل يوجد تمويل '),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='Has_Water_Meter',
            field=models.BooleanField(default=False, help_text='هل يوجد عداد مياه', verbose_name='هل يوجد عداد المياه '),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='Has_equipment',
            field=models.BooleanField(default=False, help_text='هل يوجد معدات', verbose_name=' هل يوجد معدات '),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='LegalEntity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.legalentity', verbose_name='كود المجمع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='OperatingLicense',
            field=models.BooleanField(default=False, help_text='هل يوجد رخصة تشغيل  ', verbose_name='رخصة تشغيل'),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='RequestNumber',
            field=models.PositiveIntegerField(default=0, verbose_name=' رقم الطلب '),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='SpecificationDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تخصيص الوحدة'),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='SubActivity',
            field=models.CharField(default=1, max_length=250, verbose_name=' النشاط على الواقع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='UnitModification',
            field=models.CharField(default=1, max_length=1000, verbose_name='التعديلات على الوحدة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='UnitNotWorkReasons',
            field=models.CharField(default=1, max_length=1500, verbose_name='  اسباب عدم العمل حتى الان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='UnitNotes',
            field=models.CharField(default=1, max_length=1500, verbose_name='  ملاحظات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='UnitProblems',
            field=models.CharField(default=1, max_length=1500, verbose_name=' المشاكل التى تواجهة المستثمر '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='UnitProblemsSolutions',
            field=models.CharField(default=1, max_length=1500, verbose_name='  الاجراءات بخصوص تلك المشكلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='industrialRegistry',
            field=models.BooleanField(default=False, help_text='هل يوجد سجل صناعى  ', verbose_name=' سجل صناعى'),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='LandOperatingStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.landoperatingstatus', verbose_name='حالة الوحدة التشغيلية'),
        ),
    ]
