# Generated by Django 4.0.3 on 2022-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0008_alter_specificationunitsdata_legalentity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationunitsdata',
            name='Services',
        ),
        migrations.RemoveField(
            model_name='specificationunitsdata',
            name='rent',
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='DuePriceOrrent',
            field=models.FloatField(blank=True, help_text='مستحقات الوحدة إيجار او ثمن ', null=True, verbose_name='مستحقات الوحدة'),
        ),
        migrations.AddField(
            model_name='specificationunitsdata',
            name='DueServices',
            field=models.FloatField(blank=True, null=True, verbose_name='مستحقات الخدمات'),
        ),
    ]
