# Generated by Django 4.0.3 on 2022-03-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0010_specificationunitsdata_attendmeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='UnitModification',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='التعديلات على الوحدة'),
        ),
    ]
