# Generated by Django 4.0.3 on 2022-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0011_alter_specificationunitsdata_unitmodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='UnitNotWorkReasons',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='  اسباب عدم العمل حتى الان'),
        ),
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='UnitProblems',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name=' المشاكل التى تواجهة المستثمر '),
        ),
    ]
