# Generated by Django 4.0.3 on 2022-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0012_alter_specificationunitsdata_unitnotworkreasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='UnitNotes',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='  ملاحظات'),
        ),
    ]
