# Generated by Django 4.0.3 on 2022-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0013_alter_specificationunitsdata_unitnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='SubActivity',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=' النشاط على الواقع'),
        ),
    ]
