# Generated by Django 4.0.3 on 2022-03-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0015_alter_specificationunitsdata_unitproblemssolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='GoverneratesId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.governerates', verbose_name='كود المحافظة'),
        ),
    ]
