# Generated by Django 4.0.3 on 2022-03-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0016_alter_specificationunitsdata_governeratesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='CompoundId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.compound', verbose_name='كود المجمع'),
        ),
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='GoverneratesId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.governerates', verbose_name='كود المحافظة'),
            preserve_default=False,
        ),
    ]
