# Generated by Django 4.0.3 on 2022-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0017_alter_specificationunitsdata_compoundid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='OwnerUnit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المالك'),
        ),
    ]
