# Generated by Django 4.0.3 on 2022-03-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0019_alter_specificationunitsdata_governeratesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='LegalEntity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plots_global.legalentity', verbose_name='كود الكيان القانونى'),
        ),
    ]
