# Generated by Django 3.2.12 on 2022-03-24 08:21

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0021_alter_specificationunitsdata_operatinglicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='ContactNumber',
            field=phone_field.models.PhoneField(blank=True, help_text='التليفون و الفاكسات', max_length=31, null=True, verbose_name='التليفون'),
        ),
    ]
