# Generated by Django 3.2.12 on 2022-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0022_alter_specificationunitsdata_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='ContactNumber',
            field=models.CharField(blank=True, help_text='التليفون و الفاكسات', max_length=150, null=True, verbose_name='التليفون'),
        ),
    ]
