# Generated by Django 3.2.12 on 2022-04-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_global', '0023_alter_specificationunitsdata_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationunitsdata',
            name='OwnerUnit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اسم المالك'),
        ),
    ]
